workflows:
  android-debug:
    name: Android Debug Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:

      java: 17
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: | 
          cd app
          rm -f pubspec.lock
          flutter pub get
      - name: Build APK Debug
        script: | 
          cd app
          flutter build apk --debug
    artifacts:
      - app/build/**/outputs/**/*.apk
      - app/flutter_drive.log
      - flutter_drive.log
